version: '3'
services:
  vsftpd:
    build: .
    image: stellarity/vsftpd
    ports:
      - "21:21"
      - "990:990"
      - "21000-21010:21000-21010"
    environment:
      - MODE=FTP
      - PASV_ADDRESS=127.0.0.1
      - PASV_PORT=21001
